INSERT INTO `TRANS_EDEP_DATASET.TMP_CREDOLAB_DATA_ANDROID` (
  cuid,
  seriesnumber,
  device_os,
  BQ_UPDATED_TIME,
  PARTITION_DATE,
  requested_date,
  requester,
  reference_number,
  device_id,
  device_brand,
  device_model,
  device_cpu_type,
  device_is_lying,
  device_product,
  device_is_angled,
  device_is_rooted,
  device_is_virtual,
  device_os_version,
  device_phone_type,
  device_adb_enabled,
  device_is_standing,
  device_region_code,
  device_screen_size,
  device_time_zone_id,
  device_bluetooth_on,
  device_data_roaming,
  device_emulator_name,
  device_language_code,
  device_ram_total_size,
  device_battery_status,
  device_sim_country_iso,
  device_wifi_is_enabled,
  device_next_alarm_clock,
  device_host_app_is_cloned,
  device_location_enabled,
  device_main_storage_free,
  device_main_storage_total,
  device_battery_is_charging,
  device_external_storage_free,
  device_network_operator_name,
  device_accessibility_enabled,
  device_external_storage_total,
  device_is_fingerprint_enrolled,
  device_locale_display_language,
  device_network_connection_type,
  device_usb_mass_storage_enabled,
  device_development_settings_enabled,
  ip,
  ip_loc,
  ip_city,
  ip_bogon,
  ip_postal,
  ip_region,
  ip_country,
  ip_hostname,
  ip_timezone,
  ip_privacy_tor,
  ip_privacy_vpn,
  ip_privacy_proxy,
  ip_privacy_relay,
  ip_privacy_hosting,
  permission_read_sms,
  permission_get_accounts,
  permission_read_calendar,
  permission_read_contacts,
  permission_read_media_audio,
  permission_read_media_video,
  permission_use_fingerprint,
  permission_access_wifi_state,
  permission_read_media_images,
  permission_access_network_state,
  permission_read_external_storage,
  risky_vpn_flag,
  risky_app_hider_flag,
  risky_app_cloner_flag,
  risky_tor_browser_flag,
  risky_call_center_flag,
  risky_temporary_email_flag,
  risky_virtual_android_flag,
  risky_device_id_changer_flag,
  risky_location_spoofing_flag,
  risky_anonymous_messenger_flag,
  risky_desktop_mobile_bridge_flag,
  velocity_datasets_count_all_from_ip,
  velocity_datasets_count_all_from_device_id,
  velocity_datasets_unique_device_id_from_ip,
  velocity_datasets_unique_ip_from_device_id,
  velocity_datasets_count_all_from_device_id_and_ip,
  fraud_risk_emulator,
  fraud_risk_tor_usage,
  fraud_risk_vpn_usage,
  fraud_risk_http_proxy,
  fraud_risk_new_device,
  fraud_risk_automation,
  fraud_risk_device_farm,
  fraud_risk_empty_device,
  fraud_risk_remote_access,
  fraud_risk_rooted_device,
  fraud_risk_crypto_enthusiast,
  fraud_risk_location_spoofing,
  fraud_risk_time_manipulation,
  fraud_risk_geography_mismatch,
  fraud_risk_temporary_email_usage,
  fraud_risk_device_id_changer_usage,
  fraud_risk_host_application_cloned,
  fraud_risk_application_cloner_usage,
  fraud_risk_controlled_from_computer,
  fraud_risk_anonymous_messenger_usage,
  fraud_risk_application_manipulation,
  fraud_risk_application_gambling_usage,
  fraud_risk_non_market_application_usage,
  fraud_risk_host_application_not_installed_from_market,
  fraud_risk_financial_applications_installation_surge,
  apps_free_count,
  apps_paid_count,
  apps_user_count,
  apps_games_count,
  apps_tools_count,
  apps_total_count,
  apps_beauty_count,
  apps_comics_count,
  apps_dating_count,
  apps_events_count,
  apps_others_count,
  apps_social_count,
  apps_sports_count,
  apps_system_count,
  apps_finance_count,
  apps_medical_count,
  apps_missing_count,
  apps_weather_count,
  apps_business_count,
  apps_shopping_count,
  apps_education_count,
  apps_games_card_count,
  apps_games_word_count,
  apps_lifestyle_count,
  apps_parenting_count,
  apps_content_rating_3_plus,
  apps_content_rating_7_plus,
  apps_games_board_count,
  apps_games_music_count,
  apps_content_rating_12_plus,
  apps_content_rating_16_plus,
  apps_content_rating_18_plus,
  apps_games_action_count,
  apps_games_arcade_count,
  apps_games_casino_count,
  apps_games_casual_count,
  apps_games_puzzle_count,
  apps_games_racing_count,
  apps_games_trivia_count,
  apps_photography_count,
  apps_art_and_design_count,
  apps_auto_vehicles_count,
  apps_food_and_drink_count,
  apps_house_and_home_count,
  apps_productivity_count,
  apps_communication_count,
  apps_entertainment_count,
  apps_games_strategy_count,
  apps_libraries_demo_count,
  apps_music_and_audio_count,
  apps_news_magazines_count,
  apps_games_adventure_count,
  apps_travel_and_local_count,
  apps_games_simulation_count,
  apps_personalization_count,
  apps_games_educational_count,
  apps_games_role_playing_count,
  apps_health_and_fitness_count,
  apps_tool_and_utilities_count,
  apps_books_and_reference_count,
  apps_maps_and_navigation_count,
  apps_installed_last_30_days_count,
  apps_arts_and_entertainment_count,
  apps_video_players_and_editors_count,
  apps_social_and_communications_count,
  apps_user_installed_last_30_days_count,
  apps_user_installed_last_3_months_count,
  apps_user_installed_last_6_months_count,
  apps_user_installed_last_12_months_count,
  device_age_since_first_app_install_by_user,
  typing_text_input_speed,
  typing_text_input_letters_count,
  typing_text_input_numbers_count,
  typing_input_start_with_lower_count,
  typing_input_start_with_upper_count,
  typing_input_start_with_number_count,
  typing_text_input_chars_except_num_and_letters_count,
  ui_input_delete_actions_count,
  ui_input_insert_actions_count,
  ui_input_delete_text_actions_count,
  ui_input_insert_text_actions_count,
  ui_text_input_text_prefilled_count,
  ui_text_input_text_removed_all_count,
  ui_client_interactions_time_spent_total,
  ui_client_activity_session_time_spent_total,
  ui_client_interactions_tracked_events_count,
  finger_fling_total_events_count,
  finger_scale_total_events_count,
  finger_touch_total_events_count,
  finger_scroll_total_events_count,
  finger_text_input_total_events_count,
  finger_fling_coordinates_distance_avg,
  finger_scroll_coordinates_distance_avg,
  touch_on_down_count,
  touch_on_double_tap_count,
  touch_on_long_press_count,
  anomaly_fling_rage_actions_count,
  anomaly_scale_rage_actions_count,
  anomaly_touch_rage_actions_count,
  anomaly_scroll_rage_actions_count,
  anomaly_text_input_rage_actions_count,
  expert_score,
  expert_probability,
  app_package_name,
  app_date_installed,
  app_date_last_updated,
  app_google_play_category,
  app_paid,
  app_date_installed_rank_desc
)

WITH
  json_input AS (
    SELECT
      r.cuid,
      r.series_number,
      r.device_os,
      r.BQ_UPDATED_TIME,
      r.PARTITION_DATE,
      PARSE_JSON(r.raw_data) AS parsed_json
    FROM `RAW_EDEP_DATASET.CREDOLAB_DATA_ANDROID` r
    LEFT JOIN `TRANS_EDEP_DATASET.TMP_CREDOLAB_DATA_ANDROID` t 
      ON r.reference_id = t.reference_number
      WHERE r.reference_id IS NOT NULL 
      AND t.reference_number IS NULL
      QUALIFY ROW_NUMBER() OVER (PARTITION BY r.reference_id ORDER BY PARTITION_DATE DESC) = 1

  ),
  base_metadata AS (
    SELECT
      CAST(cuid AS STRING) AS cuid,
      CAST(series_number AS STRING) AS seriesnumber,
      CAST(device_os AS STRING) AS device_os,
      BQ_UPDATED_TIME,
      PARTITION_DATE,
      CAST(JSON_VALUE(parsed_json, '$.requestedDate') AS STRING) AS requested_date,
      CAST(JSON_VALUE(parsed_json, '$.requester') AS STRING) AS requester,
      CAST(JSON_VALUE(parsed_json, '$.referenceNumber') AS STRING) AS reference_number
    FROM json_input
  ),
  insights AS (
    SELECT
      JSON_VALUE(parsed_json, '$.referenceNumber') AS reference_number,
      JSON_VALUE(i, '$.code') AS code,
      JSON_QUERY(i, '$.value') AS value
    FROM json_input, UNNEST(JSON_QUERY_ARRAY(parsed_json, '$.insights')) AS i
  ),
  deviceInfo AS (
    SELECT * EXCEPT(rn) FROM (
    SELECT reference_number,
      CAST(JSON_VALUE(value, '$.deviceId') AS STRING) AS device_id,
      CAST(JSON_VALUE(value, '$.deviceBrand') AS STRING) AS device_brand,
      CAST(JSON_VALUE(value, '$.deviceModel') AS STRING) AS device_model,
      CAST(JSON_VALUE(value, '$.deviceCPUType') AS STRING) AS device_cpu_type,
      CAST(JSON_VALUE(value, '$.deviceIsLying') AS STRING) AS device_is_lying,
      CAST(JSON_VALUE(value, '$.deviceProduct') AS STRING) AS device_product,
      CAST(JSON_VALUE(value, '$.deviceIsAngled') AS STRING) AS device_is_angled,
      CAST(JSON_VALUE(value, '$.deviceIsRooted') AS STRING) AS device_is_rooted,
      CAST(JSON_VALUE(value, '$.deviceIsVirtual') AS STRING) AS device_is_virtual,
      CAST(JSON_VALUE(value, '$.deviceOsVersion') AS STRING) AS device_os_version,
      CAST(JSON_VALUE(value, '$.devicePhoneType') AS STRING) AS device_phone_type,
      CAST(JSON_VALUE(value, '$.deviceADBEnabled') AS STRING) AS device_adb_enabled,
      CAST(JSON_VALUE(value, '$.deviceIsStanding') AS STRING) AS device_is_standing,
      CAST(JSON_VALUE(value, '$.deviceRegionCode') AS STRING) AS device_region_code,
      CAST(JSON_VALUE(value, '$.deviceScreenSize') AS STRING) AS device_screen_size,
      CAST(JSON_VALUE(value, '$.deviceTimeZoneId') AS STRING) AS device_time_zone_id,
      CAST(JSON_VALUE(value, '$.deviceBluetoothOn') AS STRING) AS device_bluetooth_on,
      CAST(JSON_VALUE(value, '$.deviceDataRoaming') AS STRING) AS device_data_roaming,
      CAST(JSON_VALUE(value, '$.deviceEmulatorName') AS STRING) AS device_emulator_name,
      CAST(JSON_VALUE(value, '$.deviceLanguageCode') AS STRING) AS device_language_code,
      CAST(JSON_VALUE(value, '$.deviceRamTotalSize') AS STRING) AS device_ram_total_size,
      CAST(JSON_VALUE(value, '$.deviceBatteryStatus') AS STRING) AS device_battery_status,
      CAST(JSON_VALUE(value, '$.deviceSimCountryIso') AS STRING) AS device_sim_country_iso,
      CAST(JSON_VALUE(value, '$.deviceWifiIsEnabled') AS STRING) AS device_wifi_is_enabled,
      CAST(JSON_VALUE(value, '$.deviceNextAlarmClock') AS STRING) AS device_next_alarm_clock,
      CAST(JSON_VALUE(value, '$.deviceHostAppIsCloned') AS STRING) AS device_host_app_is_cloned,
      CAST(JSON_VALUE(value, '$.deviceLocationEnabled') AS STRING) AS device_location_enabled,
      CAST(JSON_VALUE(value, '$.deviceMainStorageFree') AS STRING) AS device_main_storage_free,
      CAST(JSON_VALUE(value, '$.deviceMainStorageTotal') AS STRING) AS device_main_storage_total,
      CAST(JSON_VALUE(value, '$.deviceBatteryIsCharging') AS STRING) AS device_battery_is_charging,
      CAST(JSON_VALUE(value, '$.deviceExternalStorageFree') AS STRING) AS device_external_storage_free,
      CAST(JSON_VALUE(value, '$.deviceNetworkOperatorName') AS STRING) AS device_network_operator_name,
      CAST(JSON_VALUE(value, '$.deviceAccessibilityEnabled') AS STRING) AS device_accessibility_enabled,
      CAST(JSON_VALUE(value, '$.deviceExternalStorageTotal') AS STRING) AS device_external_storage_total,
      CAST(JSON_VALUE(value, '$.deviceIsFingerprintEnrolled') AS STRING) AS device_is_fingerprint_enrolled,
      CAST(JSON_VALUE(value, '$.deviceLocaleDisplayLanguage') AS STRING) AS device_locale_display_language,
      CAST(JSON_VALUE(value, '$.deviceNetworkConnectionType') AS STRING) AS device_network_connection_type,
      CAST(JSON_VALUE(value, '$.deviceUSBMassStorageEnabled') AS STRING) AS device_usb_mass_storage_enabled,
      CAST(JSON_VALUE(value, '$.deviceDevelopmentSettingsEnabled') AS STRING) AS device_development_settings_enabled,
      ROW_NUMBER() OVER(PARTITION BY reference_number ORDER BY reference_number) rn
    FROM insights WHERE code = 'deviceInfo'
    ) WHERE rn = 1
  ),
  ipInfo AS (
    SELECT * EXCEPT(rn) FROM (
    SELECT reference_number,
      CAST(JSON_VALUE(value, '$.ip') AS STRING) AS ip,
      CAST(JSON_VALUE(value, '$.loc') AS STRING) AS ip_loc,
      CAST(JSON_VALUE(value, '$.city') AS STRING) AS ip_city,
      CAST(JSON_VALUE(value, '$.bogon') AS STRING) AS ip_bogon,
      CAST(JSON_VALUE(value, '$.postal') AS STRING) AS ip_postal,
      CAST(JSON_VALUE(value, '$.region') AS STRING) AS ip_region,
      CAST(JSON_VALUE(value, '$.country') AS STRING) AS ip_country,
      CAST(JSON_VALUE(value, '$.hostname') AS STRING) AS ip_hostname,
      CAST(JSON_VALUE(value, '$.timezone') AS STRING) AS ip_timezone,
      CAST(JSON_VALUE(value, '$.privacyTor') AS STRING) AS ip_privacy_tor,
      CAST(JSON_VALUE(value, '$.privacyVpn') AS STRING) AS ip_privacy_vpn,
      CAST(JSON_VALUE(value, '$.privacyProxy') AS STRING) AS ip_privacy_proxy,
      CAST(JSON_VALUE(value, '$.privacyRelay') AS STRING) AS ip_privacy_relay,
      CAST(JSON_VALUE(value, '$.privacyHosting') AS STRING) AS ip_privacy_hosting,
      ROW_NUMBER() OVER(PARTITION BY reference_number ORDER BY reference_number) rn
    FROM insights WHERE code = 'ipInfo'
    ) WHERE rn = 1
  ),
  permissions AS (
    SELECT * EXCEPT(rn) FROM (
    SELECT reference_number,
      CAST(JSON_VALUE(value, '$.readSms') AS STRING) AS permission_read_sms,
      CAST(JSON_VALUE(value, '$.getAccounts') AS STRING) AS permission_get_accounts,
      CAST(JSON_VALUE(value, '$.readCalendar') AS STRING) AS permission_read_calendar,
      CAST(JSON_VALUE(value, '$.readContacts') AS STRING) AS permission_read_contacts,
      CAST(JSON_VALUE(value, '$.readMediaAudio') AS STRING) AS permission_read_media_audio,
      CAST(JSON_VALUE(value, '$.readMediaVideo') AS STRING) AS permission_read_media_video,
      CAST(JSON_VALUE(value, '$.useFingerprint') AS STRING) AS permission_use_fingerprint,
      CAST(JSON_VALUE(value, '$.accessWifiState') AS STRING) AS permission_access_wifi_state,
      CAST(JSON_VALUE(value, '$.readMediaImages') AS STRING) AS permission_read_media_images,
      CAST(JSON_VALUE(value, '$.accessNetworkState') AS STRING) AS permission_access_network_state,
      CAST(JSON_VALUE(value, '$.readExternalStorage') AS STRING) AS permission_read_external_storage,
      ROW_NUMBER() OVER(PARTITION BY reference_number ORDER BY reference_number) rn
    FROM insights WHERE code = 'permissions'
    ) WHERE rn = 1
  ),
  riskyApps AS (
    SELECT * EXCEPT(rn) FROM (
    SELECT reference_number,
      CAST(JSON_VALUE(value, '$.vpnFlag') AS STRING) AS risky_vpn_flag,
      CAST(JSON_VALUE(value, '$.appHiderFlag') AS STRING) AS risky_app_hider_flag,
      CAST(JSON_VALUE(value, '$.appClonerFlag') AS STRING) AS risky_app_cloner_flag,
      CAST(JSON_VALUE(value, '$.TorBrowserFlag') AS STRING) AS risky_tor_browser_flag,
      CAST(JSON_VALUE(value, '$.callCenterFlag') AS STRING) AS risky_call_center_flag,
      CAST(JSON_VALUE(value, '$.temporaryEmailFlag') AS STRING) AS risky_temporary_email_flag,
      CAST(JSON_VALUE(value, '$.virtualAndroidFlag') AS STRING) AS risky_virtual_android_flag,
      CAST(JSON_VALUE(value, '$.deviceIdChangerFlag') AS STRING) AS risky_device_id_changer_flag,
      CAST(JSON_VALUE(value, '$.locationSpoofingFlag') AS STRING) AS risky_location_spoofing_flag,
      CAST(JSON_VALUE(value, '$.anonymousMessengerFlag') AS STRING) AS risky_anonymous_messenger_flag,
      CAST(JSON_VALUE(value, '$.desktopMobileBridgeFlag') AS STRING) AS risky_desktop_mobile_bridge_flag,
      ROW_NUMBER() OVER(PARTITION BY reference_number ORDER BY reference_number) rn
    FROM insights WHERE code = 'riskyApps'
    ) WHERE rn = 1
  ),
  velocity AS (
    SELECT * EXCEPT(rn) FROM (
    SELECT reference_number,
      CAST(JSON_VALUE(value, '$.datasetsCountAllFromIp') AS STRING) AS velocity_datasets_count_all_from_ip,
      CAST(JSON_VALUE(value, '$.datasetsCountAllFromDeviceId') AS STRING) AS velocity_datasets_count_all_from_device_id,
      CAST(JSON_VALUE(value, '$.datasetsUniqueDeviceIdFromIp') AS STRING) AS velocity_datasets_unique_device_id_from_ip,
      CAST(JSON_VALUE(value, '$.datasetsUniqueIpFromDeviceId') AS STRING) AS velocity_datasets_unique_ip_from_device_id,
      CAST(JSON_VALUE(value, '$.datasetsCountAllFromDeviceIdAndIp') AS STRING) AS velocity_datasets_count_all_from_device_id_and_ip,
      ROW_NUMBER() OVER(PARTITION BY reference_number ORDER BY reference_number) rn
    FROM insights WHERE code = 'velocity'
    ) WHERE rn = 1
  ),
  fraudAlerts AS (
    SELECT * EXCEPT(rn) FROM (
    SELECT reference_number,
      CAST(JSON_VALUE(value, '$.riskEmulator') AS STRING) AS fraud_risk_emulator,
      CAST(JSON_VALUE(value, '$.riskTorUsage') AS STRING) AS fraud_risk_tor_usage,
      CAST(JSON_VALUE(value, '$.riskVpnUsage') AS STRING) AS fraud_risk_vpn_usage,
      CAST(JSON_VALUE(value, '$.riskHttpProxy') AS STRING) AS fraud_risk_http_proxy,
      CAST(JSON_VALUE(value, '$.riskNewDevice') AS STRING) AS fraud_risk_new_device,
      CAST(JSON_VALUE(value, '$.riskAutomation') AS STRING) AS fraud_risk_automation,
      CAST(JSON_VALUE(value, '$.riskDeviceFarm') AS STRING) AS fraud_risk_device_farm,
      CAST(JSON_VALUE(value, '$.riskEmptyDevice') AS STRING) AS fraud_risk_empty_device,
      CAST(JSON_VALUE(value, '$.riskRemoteAccess') AS STRING) AS fraud_risk_remote_access,
      CAST(JSON_VALUE(value, '$.riskRootedDevice') AS STRING) AS fraud_risk_rooted_device,
      CAST(JSON_VALUE(value, '$.riskCryptoEnthusiast') AS STRING) AS fraud_risk_crypto_enthusiast,
      CAST(JSON_VALUE(value, '$.riskLocationSpoofing') AS STRING) AS fraud_risk_location_spoofing,
      CAST(JSON_VALUE(value, '$.riskTimeManipulation') AS STRING) AS fraud_risk_time_manipulation,
      CAST(JSON_VALUE(value, '$.riskGeographyMismatch') AS STRING) AS fraud_risk_geography_mismatch,
      CAST(JSON_VALUE(value, '$.riskTemporaryEmailUsage') AS STRING) AS fraud_risk_temporary_email_usage,
      CAST(JSON_VALUE(value, '$.riskDeviceIdChangerUsage') AS STRING) AS fraud_risk_device_id_changer_usage,
      CAST(JSON_VALUE(value, '$.riskHostApplicationCloned') AS STRING) AS fraud_risk_host_application_cloned,
      CAST(JSON_VALUE(value, '$.riskApplicationClonerUsage') AS STRING) AS fraud_risk_application_cloner_usage,
      CAST(JSON_VALUE(value, '$.riskControlledFromComputer') AS STRING) AS fraud_risk_controlled_from_computer,
      CAST(JSON_VALUE(value, '$.riskAnonymousMessengerUsage') AS STRING) AS fraud_risk_anonymous_messenger_usage,
      CAST(JSON_VALUE(value, '$.riskApplicationManipulation') AS STRING) AS fraud_risk_application_manipulation,
      CAST(JSON_VALUE(value, '$.riskApplicationGamblingUsage') AS STRING) AS fraud_risk_application_gambling_usage,
      CAST(JSON_VALUE(value, '$.riskNonMarketApplicationUsage') AS STRING) AS fraud_risk_non_market_application_usage,
      CAST(JSON_VALUE(value, '$.riskHostApplicationNotInstalledFromMarket') AS STRING) AS fraud_risk_host_application_not_installed_from_market,
      CAST(JSON_VALUE(value, '$.riskFinancialApplicationsInstallationSurge') AS STRING) AS fraud_risk_financial_applications_installation_surge,
      ROW_NUMBER() OVER(PARTITION BY reference_number ORDER BY reference_number) rn
    FROM insights WHERE code = 'fraudAlerts'
    ) WHERE rn = 1
  ),
  appsInfo AS (
    SELECT * EXCEPT(rn) FROM (
    SELECT reference_number,
      CAST(JSON_VALUE(value, '$.appsFreeCount') AS STRING) AS apps_free_count,
      CAST(JSON_VALUE(value, '$.appsPaidCount') AS STRING) AS apps_paid_count,
      CAST(JSON_VALUE(value, '$.appsUserCount') AS STRING) AS apps_user_count,
      CAST(JSON_VALUE(value, '$.appsGamesCount') AS STRING) AS apps_games_count,
      CAST(JSON_VALUE(value, '$.appsToolsCount') AS STRING) AS apps_tools_count,
      CAST(JSON_VALUE(value, '$.appsTotalCount') AS STRING) AS apps_total_count,
      CAST(JSON_VALUE(value, '$.appsBeautyCount') AS STRING) AS apps_beauty_count,
      CAST(JSON_VALUE(value, '$.appsComicsCount') AS STRING) AS apps_comics_count,
      CAST(JSON_VALUE(value, '$.appsDatingCount') AS STRING) AS apps_dating_count,
      CAST(JSON_VALUE(value, '$.appsEventsCount') AS STRING) AS apps_events_count,
      CAST(JSON_VALUE(value, '$.appsOthersCount') AS STRING) AS apps_others_count,
      CAST(JSON_VALUE(value, '$.appsSocialCount') AS STRING) AS apps_social_count,
      CAST(JSON_VALUE(value, '$.appsSportsCount') AS STRING) AS apps_sports_count,
      CAST(JSON_VALUE(value, '$.appsSystemCount') AS STRING) AS apps_system_count,
      CAST(JSON_VALUE(value, '$.appsFinanceCount') AS STRING) AS apps_finance_count,
      CAST(JSON_VALUE(value, '$.appsMedicalCount') AS STRING) AS apps_medical_count,
      CAST(JSON_VALUE(value, '$.appsMissingCount') AS STRING) AS apps_missing_count,
      CAST(JSON_VALUE(value, '$.appsWeatherCount') AS STRING) AS apps_weather_count,
      CAST(JSON_VALUE(value, '$.appsBusinessCount') AS STRING) AS apps_business_count,
      CAST(JSON_VALUE(value, '$.appsShoppingCount') AS STRING) AS apps_shopping_count,
      CAST(JSON_VALUE(value, '$.appsEducationCount') AS STRING) AS apps_education_count,
      CAST(JSON_VALUE(value, '$.appsGamesCardCount') AS STRING) AS apps_games_card_count,
      CAST(JSON_VALUE(value, '$.appsGamesWordCount') AS STRING) AS apps_games_word_count,
      CAST(JSON_VALUE(value, '$.appsLifestyleCount') AS STRING) AS apps_lifestyle_count,
      CAST(JSON_VALUE(value, '$.appsParentingCount') AS STRING) AS apps_parenting_count,
      CAST(JSON_VALUE(value, '$."appsContentRating3+"') AS STRING) AS apps_content_rating_3_plus,
      CAST(JSON_VALUE(value, '$."appsContentRating7+"') AS STRING) AS apps_content_rating_7_plus,
      CAST(JSON_VALUE(value, '$.appsGamesBoardCount') AS STRING) AS apps_games_board_count,
      CAST(JSON_VALUE(value, '$.appsGamesMusicCount') AS STRING) AS apps_games_music_count,
      CAST(JSON_VALUE(value, '$."appsContentRating12+"') AS STRING) AS apps_content_rating_12_plus,
      CAST(JSON_VALUE(value, '$."appsContentRating16+"') AS STRING) AS apps_content_rating_16_plus,
      CAST(JSON_VALUE(value, '$."appsContentRating18+"') AS STRING) AS apps_content_rating_18_plus,
      CAST(JSON_VALUE(value, '$.appsGamesActionCount') AS STRING) AS apps_games_action_count,
      CAST(JSON_VALUE(value, '$.appsGamesArcadeCount') AS STRING) AS apps_games_arcade_count,
      CAST(JSON_VALUE(value, '$.appsGamesCasinoCount') AS STRING) AS apps_games_casino_count,
      CAST(JSON_VALUE(value, '$.appsGamesCasualCount') AS STRING) AS apps_games_casual_count,
      CAST(JSON_VALUE(value, '$.appsGamesPuzzleCount') AS STRING) AS apps_games_puzzle_count,
      CAST(JSON_VALUE(value, '$.appsGamesRacingCount') AS STRING) AS apps_games_racing_count,
      CAST(JSON_VALUE(value, '$.appsGamesTriviaCount') AS STRING) AS apps_games_trivia_count,
      CAST(JSON_VALUE(value, '$.appsPhotographyCount') AS STRING) AS apps_photography_count,
      CAST(JSON_VALUE(value, '$.appsArtAndDesignCount') AS STRING) AS apps_art_and_design_count,
      CAST(JSON_VALUE(value, '$.appsAutoVehiclesCount') AS STRING) AS apps_auto_vehicles_count,
      CAST(JSON_VALUE(value, '$.appsFoodAndDrinkCount') AS STRING) AS apps_food_and_drink_count,
      CAST(JSON_VALUE(value, '$.appsHouseAndHomeCount') AS STRING) AS apps_house_and_home_count,
      CAST(JSON_VALUE(value, '$.appsProductivityCount') AS STRING) AS apps_productivity_count,
      CAST(JSON_VALUE(value, '$.appsCommunicationCount') AS STRING) AS apps_communication_count,
      CAST(JSON_VALUE(value, '$.appsEntertainmentCount') AS STRING) AS apps_entertainment_count,
      CAST(JSON_VALUE(value, '$.appsGamesStrategyCount') AS STRING) AS apps_games_strategy_count,
      CAST(JSON_VALUE(value, '$.appsLibrariesDemoCount') AS STRING) AS apps_libraries_demo_count,
      CAST(JSON_VALUE(value, '$.appsMusicAndAudioCount') AS STRING) AS apps_music_and_audio_count,
      CAST(JSON_VALUE(value, '$.appsNewsMagazinesCount') AS STRING) AS apps_news_magazines_count,
      CAST(JSON_VALUE(value, '$.appsGamesAdventureCount') AS STRING) AS apps_games_adventure_count,
      CAST(JSON_VALUE(value, '$.appsTravelAndLocalCount') AS STRING) AS apps_travel_and_local_count,
      CAST(JSON_VALUE(value, '$.appsGamesSimulationCount') AS STRING) AS apps_games_simulation_count,
      CAST(JSON_VALUE(value, '$.appsPersonalizationCount') AS STRING) AS apps_personalization_count,
      CAST(JSON_VALUE(value, '$.appsGamesEducationalCount') AS STRING) AS apps_games_educational_count,
      CAST(JSON_VALUE(value, '$.appsGamesRolePlayingCount') AS STRING) AS apps_games_role_playing_count,
      CAST(JSON_VALUE(value, '$.appsHealthAndFitnessCount') AS STRING) AS apps_health_and_fitness_count,
      CAST(JSON_VALUE(value, '$.appsToolAndUtilitiesCount') AS STRING) AS apps_tool_and_utilities_count,
      CAST(JSON_VALUE(value, '$.appsBooksAndReferenceCount') AS STRING) AS apps_books_and_reference_count,
      CAST(JSON_VALUE(value, '$.appsMapsAndNavigationCount') AS STRING) AS apps_maps_and_navigation_count,
      CAST(JSON_VALUE(value, '$.appsInstalledLast30DaysCount') AS STRING) AS apps_installed_last_30_days_count,
      CAST(JSON_VALUE(value, '$.appsArtsAndEntertainmentCount') AS STRING) AS apps_arts_and_entertainment_count,
      CAST(JSON_VALUE(value, '$.appsVideoPlayersAndEditorsCount') AS STRING) AS apps_video_players_and_editors_count,
      CAST(JSON_VALUE(value, '$.appsSocialAndCommunicationsCount') AS STRING) AS apps_social_and_communications_count,
      CAST(JSON_VALUE(value, '$.appsUserInstalledLast30DaysCount') AS STRING) AS apps_user_installed_last_30_days_count,
      CAST(JSON_VALUE(value, '$.appsUserInstalledLast3MonthsCount') AS STRING) AS apps_user_installed_last_3_months_count,
      CAST(JSON_VALUE(value, '$.appsUserInstalledLast6MonthsCount') AS STRING) AS apps_user_installed_last_6_months_count,
      CAST(JSON_VALUE(value, '$.appsUserInstalledLast12MonthsCount') AS STRING) AS apps_user_installed_last_12_months_count,
      CAST(JSON_VALUE(value, '$.deviceAgeSinceFirstAppInstallByUser') AS STRING) AS device_age_since_first_app_install_by_user,
      ROW_NUMBER() OVER(PARTITION BY reference_number ORDER BY reference_number) rn
    FROM insights WHERE code = 'appsInfo'
    ) WHERE rn = 1
  ),
  typing AS (
    SELECT * EXCEPT(rn) FROM (
    SELECT reference_number,
      CAST(JSON_VALUE(value, '$.textInputSpeed') AS STRING) AS typing_text_input_speed,
      CAST(JSON_VALUE(value, '$.textInputLettersCount') AS STRING) AS typing_text_input_letters_count,
      CAST(JSON_VALUE(value, '$.textInputNumbersCount') AS STRING) AS typing_text_input_numbers_count,
      CAST(JSON_VALUE(value, '$.inputStartWithLowerCount') AS STRING) AS typing_input_start_with_lower_count,
      CAST(JSON_VALUE(value, '$.inputStartWithUpperCount') AS STRING) AS typing_input_start_with_upper_count,
      CAST(JSON_VALUE(value, '$.inputStartWithNumberCount') AS STRING) AS typing_input_start_with_number_count,
      CAST(JSON_VALUE(value, '$.textInputCharsExceptNumAndLettersCount') AS STRING) AS typing_text_input_chars_except_num_and_letters_count,
      ROW_NUMBER() OVER(PARTITION BY reference_number ORDER BY reference_number) rn
    FROM insights WHERE code = 'typing'
    ) WHERE rn = 1
  ),
  uiInteractions AS (
    SELECT * EXCEPT(rn) FROM (
    SELECT reference_number,
      CAST(JSON_VALUE(value, '$.inputDeleteActionsCount') AS STRING) AS ui_input_delete_actions_count,
      CAST(JSON_VALUE(value, '$.inputInsertActionsCount') AS STRING) AS ui_input_insert_actions_count,
      CAST(JSON_VALUE(value, '$.inputDeleteTextActionsCount') AS STRING) AS ui_input_delete_text_actions_count,
      CAST(JSON_VALUE(value, '$.inputInsertTextActionsCount') AS STRING) AS ui_input_insert_text_actions_count,
      CAST(JSON_VALUE(value, '$.textInputTextPrefilledCount') AS STRING) AS ui_text_input_text_prefilled_count,
      CAST(JSON_VALUE(value, '$.textInputTextRemovedAllCount') AS STRING) AS ui_text_input_text_removed_all_count,
      CAST(JSON_VALUE(value, '$.clientInteractionsTimeSpentTotal') AS STRING) AS ui_client_interactions_time_spent_total,
      CAST(JSON_VALUE(value, '$.clientActivitySessionTimeSpentTotal') AS STRING) AS ui_client_activity_session_time_spent_total,
      CAST(JSON_VALUE(value, '$.clientInteractionsTrackedEventsCount') AS STRING) AS ui_client_interactions_tracked_events_count,
      ROW_NUMBER() OVER(PARTITION BY reference_number ORDER BY reference_number) rn
    FROM insights WHERE code = 'uiInteractions'
    ) WHERE rn = 1
  ),
  fingerGestures AS (
    SELECT * EXCEPT(rn) FROM (
    SELECT reference_number,
      CAST(JSON_VALUE(value, '$.flingTotalEventsCount') AS STRING) AS finger_fling_total_events_count,
      CAST(JSON_VALUE(value, '$.scaleTotalEventsCount') AS STRING) AS finger_scale_total_events_count,
      CAST(JSON_VALUE(value, '$.touchTotalEventsCount') AS STRING) AS finger_touch_total_events_count,
      CAST(JSON_VALUE(value, '$.scrollTotalEventsCount') AS STRING) AS finger_scroll_total_events_count,
      CAST(JSON_VALUE(value, '$.textInputTotalEventsCount') AS STRING) AS finger_text_input_total_events_count,
      CAST(JSON_VALUE(value, '$.flingCoordinatesDistanceAvg') AS STRING) AS finger_fling_coordinates_distance_avg,
      CAST(JSON_VALUE(value, '$.scrollCoordinatesDistanceAvg') AS STRING) AS finger_scroll_coordinates_distance_avg,
      ROW_NUMBER() OVER(PARTITION BY reference_number ORDER BY reference_number) rn
    FROM insights WHERE code = 'fingerGestures'
    ) WHERE rn = 1
  ),
  touchActions AS (
    SELECT * EXCEPT(rn) FROM (
    SELECT reference_number,
      CAST(JSON_VALUE(value, '$.touchOnDownCount') AS STRING) AS touch_on_down_count,
      CAST(JSON_VALUE(value, '$.touchOnDoubleTapCount') AS STRING) AS touch_on_double_tap_count,
      CAST(JSON_VALUE(value, '$.touchOnLongPressCount') AS STRING) AS touch_on_long_press_count,
      ROW_NUMBER() OVER(PARTITION BY reference_number ORDER BY reference_number) rn
    FROM insights WHERE code = 'touchActions'
    ) WHERE rn = 1
  ),
  anomaly AS (
    SELECT * EXCEPT(rn) FROM (
    SELECT reference_number,
      CAST(JSON_VALUE(value, '$.flingRageActionsCount') AS STRING) AS anomaly_fling_rage_actions_count,
      CAST(JSON_VALUE(value, '$.scaleRageActionsCount') AS STRING) AS anomaly_scale_rage_actions_count,
      CAST(JSON_VALUE(value, '$.touchRageActionsCount') AS STRING) AS anomaly_touch_rage_actions_count,
      CAST(JSON_VALUE(value, '$.scrollRageActionsCount') AS STRING) AS anomaly_scroll_rage_actions_count,
      CAST(JSON_VALUE(value, '$.textInputRageActionsCount') AS STRING) AS anomaly_text_input_rage_actions_count,
      ROW_NUMBER() OVER(PARTITION BY reference_number ORDER BY reference_number) rn
    FROM insights WHERE code = 'anomaly'
    ) WHERE rn = 1
  ),
  expertScore AS (
    SELECT * EXCEPT(rn) FROM (
    SELECT reference_number,
      CAST(JSON_VALUE(value, '$.score') AS STRING) AS expert_score,
      CAST(JSON_VALUE(value, '$.probability') AS STRING) AS expert_probability,
      ROW_NUMBER() OVER(PARTITION BY reference_number ORDER BY reference_number) rn
    FROM insights WHERE code = 'expertScore'
    ) WHERE rn = 1
  ),
  lastApps AS (
    SELECT reference_number,
      CAST(JSON_VALUE(app, '$.appPackageName') AS STRING) AS app_package_name,
      CAST(JSON_VALUE(app, '$.appDateInstalled') AS STRING) AS app_date_installed,
      CAST(JSON_VALUE(app, '$.appDateLastUpdated') AS STRING) AS app_date_last_updated,
      CAST(JSON_VALUE(app, '$.appGooglePlayCategory') AS STRING) AS app_google_play_category,
      CAST(JSON_VALUE(app, '$.appPaid') AS STRING) AS app_paid,
      CAST(JSON_VALUE(app, '$.appDateInstalledRankDesc') AS STRING) AS app_date_installed_rank_desc
    FROM insights, UNNEST(JSON_QUERY_ARRAY(value)) AS app
    WHERE code = 'lastApps'
  )
SELECT
  b.cuid,
  b.seriesnumber,
  b.device_os,
  b.BQ_UPDATED_TIME,
  b.PARTITION_DATE,
  b.requested_date,
  b.requester,
  b.reference_number,
  d.device_id,
  d.device_brand,
  d.device_model,
  d.device_cpu_type,
  d.device_is_lying,
  d.device_product,
  d.device_is_angled,
  d.device_is_rooted,
  d.device_is_virtual,
  d.device_os_version,
  d.device_phone_type,
  d.device_adb_enabled,
  d.device_is_standing,
  d.device_region_code,
  d.device_screen_size,
  d.device_time_zone_id,
  d.device_bluetooth_on,
  d.device_data_roaming,
  d.device_emulator_name,
  d.device_language_code,
  d.device_ram_total_size,
  d.device_battery_status,
  d.device_sim_country_iso,
  d.device_wifi_is_enabled,
  d.device_next_alarm_clock,
  d.device_host_app_is_cloned,
  d.device_location_enabled,
  d.device_main_storage_free,
  d.device_main_storage_total,
  d.device_battery_is_charging,
  d.device_external_storage_free,
  d.device_network_operator_name,
  d.device_accessibility_enabled,
  d.device_external_storage_total,
  d.device_is_fingerprint_enrolled,
  d.device_locale_display_language,
  d.device_network_connection_type,
  d.device_usb_mass_storage_enabled,
  d.device_development_settings_enabled,
  i.ip,
  i.ip_loc,
  i.ip_city,
  i.ip_bogon,
  i.ip_postal,
  i.ip_region,
  i.ip_country,
  i.ip_hostname,
  i.ip_timezone,
  i.ip_privacy_tor,
  i.ip_privacy_vpn,
  i.ip_privacy_proxy,
  i.ip_privacy_relay,
  i.ip_privacy_hosting,
  p.permission_read_sms,
  p.permission_get_accounts,
  p.permission_read_calendar,
  p.permission_read_contacts,
  p.permission_read_media_audio,
  p.permission_read_media_video,
  p.permission_use_fingerprint,
  p.permission_access_wifi_state,
  p.permission_read_media_images,
  p.permission_access_network_state,
  p.permission_read_external_storage,
  r.risky_vpn_flag,
  r.risky_app_hider_flag,
  r.risky_app_cloner_flag,
  r.risky_tor_browser_flag,
  r.risky_call_center_flag,
  r.risky_temporary_email_flag,
  r.risky_virtual_android_flag,
  r.risky_device_id_changer_flag,
  r.risky_location_spoofing_flag,
  r.risky_anonymous_messenger_flag,
  r.risky_desktop_mobile_bridge_flag,
  v.velocity_datasets_count_all_from_ip,
  v.velocity_datasets_count_all_from_device_id,
  v.velocity_datasets_unique_device_id_from_ip,
  v.velocity_datasets_unique_ip_from_device_id,
  v.velocity_datasets_count_all_from_device_id_and_ip,
  fa.fraud_risk_emulator,
  fa.fraud_risk_tor_usage,
  fa.fraud_risk_vpn_usage,
  fa.fraud_risk_http_proxy,
  fa.fraud_risk_new_device,
  fa.fraud_risk_automation,
  fa.fraud_risk_device_farm,
  fa.fraud_risk_empty_device,
  fa.fraud_risk_remote_access,
  fa.fraud_risk_rooted_device,
  fa.fraud_risk_crypto_enthusiast,
  fa.fraud_risk_location_spoofing,
  fa.fraud_risk_time_manipulation,
  fa.fraud_risk_geography_mismatch,
  fa.fraud_risk_temporary_email_usage,
  fa.fraud_risk_device_id_changer_usage,
  fa.fraud_risk_host_application_cloned,
  fa.fraud_risk_application_cloner_usage,
  fa.fraud_risk_controlled_from_computer,
  fa.fraud_risk_anonymous_messenger_usage,
  fa.fraud_risk_application_manipulation,
  fa.fraud_risk_application_gambling_usage,
  fa.fraud_risk_non_market_application_usage,
  fa.fraud_risk_host_application_not_installed_from_market,
  fa.fraud_risk_financial_applications_installation_surge,
  ainfo.apps_free_count,
  ainfo.apps_paid_count,
  ainfo.apps_user_count,
  ainfo.apps_games_count,
  ainfo.apps_tools_count,
  ainfo.apps_total_count,
  ainfo.apps_beauty_count,
  ainfo.apps_comics_count,
  ainfo.apps_dating_count,
  ainfo.apps_events_count,
  ainfo.apps_others_count,
  ainfo.apps_social_count,
  ainfo.apps_sports_count,
  ainfo.apps_system_count,
  ainfo.apps_finance_count,
  ainfo.apps_medical_count,
  ainfo.apps_missing_count,
  ainfo.apps_weather_count,
  ainfo.apps_business_count,
  ainfo.apps_shopping_count,
  ainfo.apps_education_count,
  ainfo.apps_games_card_count,
  ainfo.apps_games_word_count,
  ainfo.apps_lifestyle_count,
  ainfo.apps_parenting_count,
  ainfo.apps_content_rating_3_plus,
  ainfo.apps_content_rating_7_plus,
  ainfo.apps_games_board_count,
  ainfo.apps_games_music_count,
  ainfo.apps_content_rating_12_plus,
  ainfo.apps_content_rating_16_plus,
  ainfo.apps_content_rating_18_plus,
  ainfo.apps_games_action_count,
  ainfo.apps_games_arcade_count,
  ainfo.apps_games_casino_count,
  ainfo.apps_games_casual_count,
  ainfo.apps_games_puzzle_count,
  ainfo.apps_games_racing_count,
  ainfo.apps_games_trivia_count,
  ainfo.apps_photography_count,
  ainfo.apps_art_and_design_count,
  ainfo.apps_auto_vehicles_count,
  ainfo.apps_food_and_drink_count,
  ainfo.apps_house_and_home_count,
  ainfo.apps_productivity_count,
  ainfo.apps_communication_count,
  ainfo.apps_entertainment_count,
  ainfo.apps_games_strategy_count,
  ainfo.apps_libraries_demo_count,
  ainfo.apps_music_and_audio_count,
  ainfo.apps_news_magazines_count,
  ainfo.apps_games_adventure_count,
  ainfo.apps_travel_and_local_count,
  ainfo.apps_games_simulation_count,
  ainfo.apps_personalization_count,
  ainfo.apps_games_educational_count,
  ainfo.apps_games_role_playing_count,
  ainfo.apps_health_and_fitness_count,
  ainfo.apps_tool_and_utilities_count,
  ainfo.apps_books_and_reference_count,
  ainfo.apps_maps_and_navigation_count,
  ainfo.apps_installed_last_30_days_count,
  ainfo.apps_arts_and_entertainment_count,
  ainfo.apps_video_players_and_editors_count,
  ainfo.apps_social_and_communications_count,
  ainfo.apps_user_installed_last_30_days_count,
  ainfo.apps_user_installed_last_3_months_count,
  ainfo.apps_user_installed_last_6_months_count,
  ainfo.apps_user_installed_last_12_months_count,
  ainfo.device_age_since_first_app_install_by_user,
  ty.typing_text_input_speed,
  ty.typing_text_input_letters_count,
  ty.typing_text_input_numbers_count,
  ty.typing_input_start_with_lower_count,
  ty.typing_input_start_with_upper_count,
  ty.typing_input_start_with_number_count,
  ty.typing_text_input_chars_except_num_and_letters_count,
  ui.ui_input_delete_actions_count,
  ui.ui_input_insert_actions_count,
  ui.ui_input_delete_text_actions_count,
  ui.ui_input_insert_text_actions_count,
  ui.ui_text_input_text_prefilled_count,
  ui.ui_text_input_text_removed_all_count,
  ui.ui_client_interactions_time_spent_total,
  ui.ui_client_activity_session_time_spent_total,
  ui.ui_client_interactions_tracked_events_count,
  fg.finger_fling_total_events_count,
  fg.finger_scale_total_events_count,
  fg.finger_touch_total_events_count,
  fg.finger_scroll_total_events_count,
  fg.finger_text_input_total_events_count,
  fg.finger_fling_coordinates_distance_avg,
  fg.finger_scroll_coordinates_distance_avg,
  ta.touch_on_down_count,
  ta.touch_on_double_tap_count,
  ta.touch_on_long_press_count,
  an.anomaly_fling_rage_actions_count,
  an.anomaly_scale_rage_actions_count,
  an.anomaly_touch_rage_actions_count,
  an.anomaly_scroll_rage_actions_count,
  an.anomaly_text_input_rage_actions_count,
  es.expert_score,
  es.expert_probability,
  la.app_package_name,
  la.app_date_installed,
  la.app_date_last_updated,
  la.app_google_play_category,
  la.app_paid,
  la.app_date_installed_rank_desc
FROM base_metadata b
LEFT JOIN deviceInfo d ON b.reference_number = d.reference_number
LEFT JOIN ipInfo i ON b.reference_number = i.reference_number
LEFT JOIN permissions p ON b.reference_number = p.reference_number
LEFT JOIN riskyApps r ON b.reference_number = r.reference_number
LEFT JOIN velocity v ON b.reference_number = v.reference_number
LEFT JOIN fraudAlerts fa ON b.reference_number = fa.reference_number
LEFT JOIN appsInfo ainfo ON b.reference_number = ainfo.reference_number
LEFT JOIN typing ty ON b.reference_number = ty.reference_number
LEFT JOIN uiInteractions ui ON b.reference_number = ui.reference_number
LEFT JOIN fingerGestures fg ON b.reference_number = fg.reference_number
LEFT JOIN touchActions ta ON b.reference_number = ta.reference_number
LEFT JOIN anomaly an ON b.reference_number = an.reference_number
LEFT JOIN expertScore es ON b.reference_number = es.reference_number
LEFT JOIN lastApps la ON b.reference_number = la.reference_number;
